# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: MyHostedVM
    steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'acrconnection'
          repository: 'infymstestcontainers'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
      - script: |
          echo 'start installing'
          wget https://github.com/aquasecurity/trivy/releases/download/v$(trivyVersion)/trivy_$(trivyVersion)_Linux-64bit.deb
          sudo dpkg -i trivy_$(trivyVersion)_Linux-64bit.deb
          trivy -v
        displayName: 'Download and install Trivy'