# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: MyHostedVM
    steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'acrconnection'
          repository: $(imageName)
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
      - task: CmdLine@2
        displayName: Trivy Scan
        inputs:
          script: |
            echo Scanning Started
            echo $(registryName)
            echo $(imageName)
            echo $(tag)
            echo $(registryName)/$(imageName):$(tag)
            echo check variable completed 
             #trivy image $(registryName)/$(imageName):$(tag)#
            trivy image --severity LOW,MEDIUM --format template --template "@templates/junit.tpl" -o junit-report-low-med.xml $(registryName)/$(imageName):$(tag
            
