# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: MyHostedVM
    steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'acrconnection'
          repository: 'infymstestcontainers'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
      - script: |
          echo 'start installing'
          sudo apt --fix-broken install
        displayName: 'Download and install Trivy'