# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: MyHostedVM
    steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'acrconnection'
          repository: $(imageName)
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
      - task: CmdLine@2
        displayName: Trivy Scan
        inputs:
          script: |
            echo Scanning Started
            echo $(imageName)
            echo $(tag)
            echo check variable completed 
            trivy image --exit-code 0 --severity LOW,MEDIUM $(imageName):$(tag)
            trivy image --exit-code 1 --severity HIGH,CRITICAL $(imageName):$(tag)
            
